name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Meteor
      run: |
        curl https://install.meteor.com/ | sh
        export PATH="$HOME/.meteor:$PATH"
        echo "$HOME/.meteor" >> $GITHUB_PATH
        
    - name: Verify Meteor installation
      run: meteor --version
      
    - name: Install dependencies
      run: meteor npm install
      
    - name: Run tests to verify build
      run: meteor test --once --driver-package meteortesting:mocha